# Generated by Django 4.0.3 on 2022-05-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
