# Generated by Django 4.0.3 on 2022-05-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veer', '0005_alter_person_date_alter_person_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
